name: Publish Firefox Add-on
on:
  push:
    tags:
      - 'v*'
    paths:
      - 'extensions/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extensions

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: extensions/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Update version in configs
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          # Update version in manifest.json
          jq ".version = \"$VERSION\"" manifest.json > manifest.json.tmp && mv manifest.json.tmp manifest.json
          # Update version in package.json
          jq ".version = \"$VERSION\"" package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Build add-on
        run: |
          npm run build

      - name: Sign and publish add-on
        env:
          WEB_EXT_API_KEY: ${{ secrets.AMO_JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_JWT_SECRET }}
        run: |
          #web-ext sign --api-key=$WEB_EXT_API_KEY --api-secret=$WEB_EXT_API_SECRET --source-dir ./
          npm run sign
